spring.application.name=esg

spring.datasource.url=jdbc:oracle:thin:@//oracle.fiap.com.br:1521/orcl
api.external.key=${API_KEY_ZIPCODE}
spring.datasource.username=${DB_USERNAMEE}
spring.datasource.password=${DB_PASS}
api.security.token.secret=${JWT_SECRET:123}

spring.docker.compose.enabled=false
spring.flyway.enabled=false

spring.jpa.hibernate.ddl-auto=update

spring.flyway.locations=classpath:db/migration

spring.flyway.baseline-on-migrate=true
spring.flyway.schemas=RM559755

