


CREATE TABLE USUARIO_ESG (
                             ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                             NOME VARCHAR2(255) NOT NULL,
                             EMAIL VARCHAR2(255) NOT NULL UNIQUE,
                             SENHA VARCHAR2(255) NOT NULL,
                             DELETED NUMBER(1) DEFAULT 0,
                             CEP VARCHAR2(20) NOT NULL,
                             LOGRADOURO VARCHAR2(255) NOT NULL,
                             BAIRRO VARCHAR2(255) NOT NULL,
                             LOCALIDADE VARCHAR2(255) NOT NULL,
                             UF VARCHAR2(2) NOT NULL,
                             LAT NUMBER(10, 6),
                             LNG NUMBER(10, 6)
);


CREATE TABLE PONTOCOLETA_ESG (
                                 ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                 NOME VARCHAR2(255) NOT NULL,
                                 STATUSPONTOGERAL VARCHAR2(50),
                                 CEP VARCHAR2(20) NOT NULL,
                                 LOGRADOURO VARCHAR2(255) NOT NULL,
                                 BAIRRO VARCHAR2(255) NOT NULL,
                                 LOCALIDADE VARCHAR2(255) NOT NULL,
                                 UF VARCHAR2(2) NOT NULL,
                                 LAT NUMBER(10, 6),
                                 LNG NUMBER(10, 6)


);


CREATE TABLE CAPACIDADEPONTO_ESG (
                                     ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                     PONTO_COLETA_ID NUMBER,
                                     TIPOMATERIAL VARCHAR2(50),
                                     CAPACIDADE NUMBER,
                                     QUANTIDADEATUAL NUMBER,
                                     STATUSCAPACIDADE VARCHAR2(50),
                                     CONSTRAINT FK_CAPACIDADE_PONTO FOREIGN KEY (PONTO_COLETA_ID) REFERENCES PONTOCOLETA_ESG(ID)
);


CREATE TABLE COLETA_ESG (
                            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            PONTO_COLETA_ID NUMBER,
                            USUARIO_ID NUMBER,
                            TIPO_MATERIAL VARCHAR2(50),
                            QUANTIDADE NUMBER(10,0),
                            DATA_COLETA TIMESTAMP
                            CONSTRAINT FK_COLETA_PONTO FOREIGN KEY (PONTO_COLETA_ID) REFERENCES PONTOCOLETA_ESG(ID),
                            CONSTRAINT FK_COLETA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO_ESG(ID)
);

CREATE TABLE NOTIFICACAO_esg (
                                 ID GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                 PONTO_COLETA_ID NUMBER(19,0),
                                 MENSAGEM VARCHAR2(500),
                                 DATA_HORA TIMESTAMP,
                                 STATUS VARCHAR2(50)
);


ALTER TABLE COLETA_ESG ADD (
    TIPO_MATERIAL VARCHAR2(50),
    QUANTIDADE NUMBER(10,0),
    DATA_COLETA TIMESTAMP
    );



CREATE TABLE NOTIFICACAO_ESG (
                                 ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                 PONTO_COLETA_ID NUMBER(19,0),
                                 MENSAGEM VARCHAR2(500),
                                 DATA_HORA TIMESTAMP,
                                 STATUS VARCHAR2(50)
);


ALTER TABLE NOTIFICACAO_ESG
    ADD CONSTRAINT FK_NOTIFICACAO_PONTO
        FOREIGN KEY (PONTO_COLETA_ID)
            REFERENCES PONTOCOLETA_ESG(ID);
